=== RapidInfoSys/Rapid/WebContent/WEB-INF/schemas/action.xsd
<?xml version="1.0" encoding="ISO-8859-1" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:annotation>
		<xs:documentation>The schema for .action.xml files</xs:documentation>
	</xs:annotation>
	<xs:element name="actions">
		<xs:annotation>
			<xs:documentation>Each .action.xml file can describe several actions
			</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="action" minOccurs="1" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>The action xml is turned into json and loaded
							into the designer where it is used to create new objects
						</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="type">
								<xs:annotation>
									<xs:documentation>The action type is used to uniquely identify
										this control, it should not contain spaces or punctuation
									</xs:documentation>
								</xs:annotation>
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:pattern value="[a-zA-Z0-9_]{1,}" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="name">
								<xs:annotation>
									<xs:documentation>The action name is presented to users when
										describing, or logging something about this action
									</xs:documentation>
								</xs:annotation>
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="1" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="class">
								<xs:annotation>
									<xs:documentation>Each action must have a Java class, in the
										classpath, that extends com.rapid.desktop.Action
									</xs:documentation>
								</xs:annotation>
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="1" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="addToNewApplications" type="xs:boolean"
								minOccurs="0">
								<xs:annotation>
									<xs:documentation>If set to true the action will be added to
										new applications when they are created
									</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="resources" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="resource" minOccurs="1"
											maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="type">
														<xs:annotation>
															<xs:documentation>The javascriptFile and cssFile are
																written into the document includes, the plain javascript
																is written to the rapid.js file and the plain css is
																written to the application rapid.css file
															</xs:documentation>
														</xs:annotation>
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:enumeration value="javascriptFile" />
																<xs:enumeration value="cssFile" />
																<xs:enumeration value="javascript" />
																<xs:enumeration value="css" />
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="contents">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:minLength value="1" />
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="properties" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="property" minOccurs="1"
											maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="key">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:minLength value="1" />
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="name">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:minLength value="1" />
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="setConstructValueFunction"
														minOccurs="0">
														<xs:annotation>
															<xs:documentation>Leave this out to not set a property
																value when the control is constructed
															</xs:documentation>
														</xs:annotation>
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:minLength value="1" />
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="changeValueJavaScript">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:minLength value="1" />
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="getValuesFunction" minOccurs="0">
														<xs:annotation>
															<xs:documentation>Possible values that can be used to
																create selects, radio groups, etc
															</xs:documentation>
														</xs:annotation>
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:minLength value="1" />
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="actionJavaScript" minOccurs="0">
								<xs:annotation>
									<xs:documentation>This is the client-side JavaScript that will
										be called, that actually performs the action. Typically the
										properties will be passed in
									</xs:documentation>
								</xs:annotation>
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="1" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== RapidInfoSys/Rapid/WebContent/WEB-INF/actions/key.action.xml
<?xml version="1.0" encoding="UTF-8" ?>
<actions xmlVersion="1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schemas/action.xsd">

<!-- 

Copyright (C) 2018 - Gareth Edwards / Rapid Information Systems

gareth.edwards@rapid-is.co.uk


This file is part of the Rapid Application Platform

Rapid is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version. The terms require you to include
the original copyright, and the license notice in all redistributions.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
in a file named "COPYING".  If not, see <http://www.gnu.org/licenses/>.

 -->

    <action>
    
        <type>key</type>        
        <name>Key</name>	        
	    <class>com.rapid.actions.Key</class>
	    <helpHtml>This action checks key events and runs child actions accordingly. If added to the page it will listen to all page key down events.</helpHtml>
	    
	    <addToNewApplications>true</addToNewApplications>
	     	    	
	    <properties>
	        	        
	        <property>
	            <key>keyCode</key>
	            <name>Key</name>
	            <setConstructValueFunction>return "";</setConstructValueFunction>
	            <changeValueJavaScript>select</changeValueJavaScript>
	            <getValuesFunction>return [["","Please select...",""],["8","backspace"],["9","tab"],["13","enter"],["16","shift"],["17","ctrl"],["18","alt"],["19","pause/break"],["20","capslock"],["27","escape"],["33","pageup"],["34","pagedown"],["35","end"],["36","home"],["37","leftarrow"],["38","uparrow"],["39","rightarrow"],["40","downarrow"],["45","insert"],["46","delete"],["48","0"],["49","1"],["50","2"],["51","3"],["52","4"],["53","5"],["54","6"],["55","7"],["56","8"],["57","9"],["65","a"],["66","b"],["67","c"],["68","d"],["69","e"],["70","f"],["71","g"],["72","h"],["73","i"],["74","j"],["75","k"],["76","l"],["77","m"],["78","n"],["79","o"],["80","p"],["81","q"],["82","r"],["83","s"],["84","t"],["85","u"],["86","v"],["87","w"],["88","x"],["89","y"],["90","z"],["91","leftwindowkey"],["92","rightwindowkey"],["93","selectkey"],["96","numpad0"],["97","numpad1"],["98","numpad2"],["99","numpad3"],["100","numpad4"],["101","numpad5"],["102","numpad6"],["103","numpad7"],["104","numpad8"],["105","numpad9"],["106","multiply"],["107","add"],["109","subtract"],["110","decimalpoint"],["111","divide"],["112","f1"],["113","f2"],["114","f3"],["115","f4"],["116","f5"],["117","f6"],["118","f7"],["119","f8"],["120","f9"],["121","f10"],["122","f11"],["123","f12"],["144","numlock"],["145","scrolllock"],["186","semi-colon"],["187","equalsign"],["188","comma"],["189","dash"],["190","period"],["191","forwardslash"],["192","graveaccent"],["219","openbracket"],["220","backslash"],["221","closebraket"],["222","singlequote"],];</getValuesFunction>
	            <helpHtml>The key to respond to.</helpHtml>
	        </property>
	        
	        <property>
	            <key>extra</key>
	            <name>Extra</name>
	            <setConstructValueFunction>return "";</setConstructValueFunction>
	            <changeValueJavaScript>select</changeValueJavaScript>
	            <getValuesFunction>return [["","Please select...",""],["altKey","alt"],["ctrlKey","ctrl"],["metaKey","meta"],["shiftKey","shift"],["ctrlKey,altKey","ctrl + alt"],["ctrlKey,shiftKey","ctrl + shift"]];</getValuesFunction>
	            <helpHtml>Extra behaviour that may influence the desired behaviour like holding the shift key.</helpHtml>
	        </property>
	        	        	    	        
	        <property>
	            <key>actions</key>
	            <name>Actions</name>
	            <changeValueJavaScript>childActions</changeValueJavaScript>
	            <helpHtml>Actions to perform on the key event.</helpHtml>
	        </property>
	        
	        <property>
	            <key>preventDefault</key>
	            <name>Prevent default</name>
	            <changeValueJavaScript>checkbox</changeValueJavaScript>
	            <helpHtml>Whether to try to prevent the default behaviour of this key. For example to stop F11 showing the page in full screen</helpHtml>
	        </property>
	        
	    </properties>
	    	        
    </action> 
</actions>

=== RapidInfoSys/Rapid/WebContent/WEB-INF/actions/validation.action.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<actions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schemas/action.xsd">
    <action>
    
        <type>validation</type>
        <name>Validation</name>	        
	    <class>com.rapid.actions.Validation</class>	
	    
	    <addToNewApplications>true</addToNewApplications>    
	    
	    <properties>
	        <property>
	            <key>controls</key>
	            <name>Controls</name>
	            <changeValueJavaScript>validationControls</changeValueJavaScript>	 
	        </property>
	        <property>
	            <key>showMessages</key>
	            <name>Show messages</name>
	            <setConstructValueFunction>return true;</setConstructValueFunction>
	            <changeValueJavaScript>checkbox</changeValueJavaScript>	 
	        </property>
	        <property>
	            <key>stopActions</key>
	            <name>Stop actions</name>
	            <setConstructValueFunction>return true;</setConstructValueFunction>
	            <changeValueJavaScript>checkbox</changeValueJavaScript>	 
	        </property>
	        <property>
	            <key>passActions</key>
	            <name>Pass actions</name>
	            <changeValueJavaScript>childActions</changeValueJavaScript>	 
	        </property>
	        <property>
	            <key>failActions</key>
	            <name>Fail actions</name>
	            <changeValueJavaScript>childActions</changeValueJavaScript>	 
	        </property>
	    </properties>
	    
	    <actionJavaScript>
	        <![CDATA[   
function Action_validation(ev, validations, showMessages) {
	var valid = true;
	for (var i in validations) {
		var validation = validations[i];
		var value = window["getData_" + validation.controlType](ev, validation.controlId, validation.field, validation.details);
		if (validation.validationType == "javascript") {						
			var validationFunction = new Function("value", validation.javaScript);
			var failMessage = validationFunction.apply(this, [value]);
			if (failMessage) {
				if (showMessages) showValidationMessage(validation.controlId, failMessage);
				valid = false;
			} else {
				if (showMessages) hideValidationMessage(validation.controlId);
			}
		} else {
			if ((value && value.match(new RegExp(validation.regEx)))||(!value && validation.allowNulls)) {
				// passed
				if (showMessages) hideValidationMessage(validation.controlId);				
			} else {
				// failed
				if (showMessages) showValidationMessage(validation.controlId, validation.message);
				valid = false;					
			}	
		}	
	}	
	return valid;
}	        ]]>
	    </actionJavaScript> 
    </action> 
    
</actions>

=== RapidInfoSys/Rapid/WebContent/WEB-INF/actions/database.action.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<actions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schemas/action.xsd">
    <action>
        
        <type>database</type>
        <version>1</version>
        <name>Database</name>	        
	    <class>com.rapid.actions.Database</class>	
	    
	    <addToNewApplications>true</addToNewApplications> 
	    	    
	    <properties>
	        <property>
	            <key>query</key>
	            <name>Query</name>
	            <changeValueJavaScript>databaseQuery</changeValueJavaScript>	 
	        </property>	  
	        <property>
	            <key>showLoading</key>
	            <name>Loading animation</name>
	            <changeValueJavaScript>checkbox</changeValueJavaScript>	 
	        </property>	
	        <property>
	            <key>successActions</key>
	            <name>Success actions</name>
	            <changeValueJavaScript>childActions</changeValueJavaScript>	 
	        </property>
	        <property>
	            <key>errorActions</key>
	            <name>Error actions</name>
	            <changeValueJavaScript>childActions</changeValueJavaScript>	 
	        </property>      
	    </properties>	 
	    	    	      
	    <actionJavaScript>
	        <![CDATA[ 
function Action_database(data, outputs) {
	if (data && outputs) {
		for (var i in outputs) {
			var output = outputs[i];			
			window["setData_" + output.type](output.id, data, output.field, output.details);
		}
	}
}	        ]]>
	    </actionJavaScript>
	    	    	    
    </action> 
</actions>

=== RapidInfoSys/Rapid/WebContent/WEB-INF/actions/timer.action.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<actions xmlVersion="1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schemas/action.xsd">
 
 <!-- 

Copyright (C) 2014 - Gareth Edwards / Rapid Information Systems

gareth.edwards@rapid-is.co.uk


This file is part of the Rapid Application Platform

RapidSOA is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version. The terms require you to include
the original copyright, and the license notice in all redistributions.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
in a file named "COPYING".  If not, see <http://www.gnu.org/licenses/>.

 -->
 
    <action>
    
        <type>timer</type>       
        <name>Timer</name>	        
	    <class>com.rapid.actions.Timer</class>	
	    
	    <properties>
	        
	        <property>
	            <key>duration</key>
	            <name>Duration (milliseconds)</name>	            
	            <setConstructValueFunction>return 1000;</setConstructValueFunction>
	            <changeValueJavaScript>integer</changeValueJavaScript>
	        </property>	
	            	
	    	<property>
	            <key>repeat</key>
	            <name>Repeat</name>
	            <setConstructValueFunction>return false;</setConstructValueFunction>
	            <changeValueJavaScript>checkbox</changeValueJavaScript>	            	
	        </property>
	        
	        <property>
	            <key>actions</key>
	            <name>Actions</name>
	            <changeValueJavaScript>childActions</changeValueJavaScript>	
	        </property>
	        
	    </properties>
	        	      	    
    </action> 
    
</actions>

=== RapidInfoSys/Rapid/WebContent/WEB-INF/actions/webservice.action.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<actions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schemas/action.xsd">
    <action>
    
        <type>webservice</type>
        <name>Webservice</name>	        
	    <class>com.rapid.actions.Webservice</class>
	    
	    <addToNewApplications>true</addToNewApplications>
	    
	    <resources>
	    	<resource>
	    		<type>javascript</type>
	    		<contents>
	    			<![CDATA[
// this global associative array tracks the webserviceAction call sequences for each action	    			
var _webserviceActionSequence = [];	    

// this global associative array holds the greates sequence received back     			
var _webserviceActionMaxSequence = [];	

// this function returns an incrementing sequence for each database action call so long-running slow queries don't overrwrite fast later queries
function getWebserviceActionSequence(actionId) {
	// retrieve the current sequence for the action
	var sequence = _webserviceActionSequence[actionId];
	// if null set to 0
	if (!sequence) sequence = 0
	// increment
	sequence++;
	// store
	_webserviceActionSequence[actionId] = sequence;
	// pass back
	return sequence;
}	

// this function sets the max to 0 if null
function getWebserviceActionMaxSequence(actionId) {
	// retrieve the current sequence for the action
	var sequence = _webserviceActionMaxSequence[actionId];
	// if undefined
	if (sequence === undefined) {
		// set to 0
		sequence = 0;
		// retain for next time
		_webserviceActionMaxSequence[actionId] = sequence;
	}
	// pass back
	return sequence;
}			
	    			]]>
	    		</contents>
	    	</resource>
	    </resources>
	    	 
	    <properties>
	        <property>
	            <key>request</key>
	            <name>Request</name>
	            <changeValueJavaScript>webserviceRequest</changeValueJavaScript>	 
	        </property>	  
	        <property>
	            <key>showLoading</key>
	            <name>Loading animation</name>
	            <changeValueJavaScript>checkbox</changeValueJavaScript>	 
	        </property>	
	        <property>
	            <key>successActions</key>
	            <name>Success actions</name>
	            <changeValueJavaScript>childActions</changeValueJavaScript>	 
	        </property>
	        <property>
	            <key>errorActions</key>
	            <name>Error actions</name>
	            <changeValueJavaScript>childActions</changeValueJavaScript>	 
	        </property>      
	    </properties>	   
	     
	    <actionJavaScript>
	        <![CDATA[ 
function Action_webservice(actionId, data, outputs) {
	// only if there are data and outputs
	if (data && outputs) {
		// only if this is the latest sequence
		if (data.sequence > getWebserviceActionMaxSequence(actionId)) {
			// retain this as the lastest sequence
			_webserviceActionMaxSequence[actionId] = data.sequence;
			// loop the outputs
			for (var i in outputs) {
				var output = outputs[i];			
				window["setData_" + output.type](output.id, data, output.field, output.details);
			}
		}
	}
}	        ]]>
	    </actionJavaScript>   
	    
    </action> 
</actions>
