=== RapidInfoSys/Rapid/WebContent/WEB-INF/schemas/action.xsd
<?xml version="1.0" encoding="ISO-8859-1" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:annotation>
		<xs:documentation>The schema for .action.xml files</xs:documentation>
	</xs:annotation>
	<xs:element name="actions">
		<xs:annotation>
			<xs:documentation>Each .action.xml file can describe several actions
			</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="action" minOccurs="1" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>The action xml is turned into json and loaded
							into the designer where it is used to create new objects
						</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="type">
								<xs:annotation>
									<xs:documentation>The action type is used to uniquely identify
										this control, it should not contain spaces or punctuation
									</xs:documentation>
								</xs:annotation>
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:pattern value="[a-zA-Z0-9_]{1,}" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="name">
								<xs:annotation>
									<xs:documentation>The action name is presented to users when
										describing, or logging something about this action
									</xs:documentation>
								</xs:annotation>
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="1" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="class">
								<xs:annotation>
									<xs:documentation>Each action must have a Java class, in the
										classpath, that extends com.rapid.desktop.Action
									</xs:documentation>
								</xs:annotation>
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="1" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="addToNewApplications" type="xs:boolean"
								minOccurs="0">
								<xs:annotation>
									<xs:documentation>If set to true the action will be added to
										new applications when they are created
									</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="resources" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="resource" minOccurs="1"
											maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="type">
														<xs:annotation>
															<xs:documentation>The javascriptFile and cssFile are
																written into the document includes, the plain javascript
																is written to the rapid.js file and the plain css is
																written to the application rapid.css file
															</xs:documentation>
														</xs:annotation>
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:enumeration value="javascriptFile" />
																<xs:enumeration value="cssFile" />
																<xs:enumeration value="javascript" />
																<xs:enumeration value="css" />
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="contents">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:minLength value="1" />
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="properties" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="property" minOccurs="1"
											maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="key">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:minLength value="1" />
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="name">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:minLength value="1" />
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="setConstructValueFunction"
														minOccurs="0">
														<xs:annotation>
															<xs:documentation>Leave this out to not set a property
																value when the control is constructed
															</xs:documentation>
														</xs:annotation>
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:minLength value="1" />
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="changeValueJavaScript">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:minLength value="1" />
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="getValuesFunction" minOccurs="0">
														<xs:annotation>
															<xs:documentation>Possible values that can be used to
																create selects, radio groups, etc
															</xs:documentation>
														</xs:annotation>
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:minLength value="1" />
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="actionJavaScript" minOccurs="0">
								<xs:annotation>
									<xs:documentation>This is the client-side JavaScript that will
										be called, that actually performs the action. Typically the
										properties will be passed in
									</xs:documentation>
								</xs:annotation>
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="1" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== RapidInfoSys/Rapid/WebContent/WEB-INF/actions/datacopy.action.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<actions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schemas/action.xsd">
    <action>
        
        <type>dataCopy</type>
        <version>1</version>
        <name>Data copy</name>	        
	    <class>com.rapid.actions.Datacopy</class>	 
	    
	    <addToNewApplications>true</addToNewApplications>
	    
	    <properties>
	    
	        <property>
	            <key>dataSource</key>
	            <name>Source</name>
	            <changeValueJavaScript>select</changeValueJavaScript>
	            <getValuesFunction>
	                <![CDATA[
return "<option value=''>None</option>" + getInputOptions(this.dataSource);         
	                ]]>
	            </getValuesFunction>	
	        </property>
	        
	        <property>
	            <key>dataSourceField</key>
	            <name>Source field</name>
	            <changeValueJavaScript>text</changeValueJavaScript>
	            <getValuesFunction>return "";</getValuesFunction>
	        </property>	  
	        
	        <property>
	            <key>dataDestinations</key>
	            <name>Destinations</name>
	            <changeValueJavaScript>dataDestinations</changeValueJavaScript> 
	        </property>  
	          
	    </properties>	    
	    <actionJavaScript>
	        <![CDATA[ 
function Action_datacopy(data, outputs) {
	if (outputs) {
		for (var i in outputs) {
			var output = outputs[i];			
			window["setData_" + output.type](output.id, data, output.field, output.details);
		}
	}
}	        ]]>
	    </actionJavaScript>
	       
    </action>     
</actions>

=== RapidInfoSys/Rapid/WebContent/WEB-INF/actions/custom.action.xml
<?xml version="1.0" encoding="UTF-8" ?>
<actions xmlVersion="1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schemas/action.xsd">

<!-- 

Copyright (C) 2018 - Gareth Edwards / Rapid Information Systems

gareth.edwards@rapid-is.co.uk


This file is part of the Rapid Application Platform

Rapid is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version. The terms require you to include
the original copyright, and the license notice in all redistributions.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
in a file named "COPYING".  If not, see <http://www.gnu.org/licenses/>.

 -->

    <action>
    
        <type>custom</type>
        <name>Custom</name>
	    <class>com.rapid.actions.Custom</class>
	    <helpHtml>This action allows you to enter customised Javascript for complete flexibility. If you find your page becomes blank when viewing it could be that an error in your code has occurred here.</helpHtml>
	    
	    <properties>
	        <property>
	            <key>javascript</key>
	            <name>JavaScript</name>
	            <setConstructValueFunction>return "// Enter JavaScript here. The event object is passed in as \"ev\"";</setConstructValueFunction>
	            <changeValueJavaScript>bigtext</changeValueJavaScript>
	            <helpHtml>Allows you to create customised actions using JavaScript. Recommended for advanced programmers.</helpHtml>
	        </property>
	    </properties>
	    
    </action> 
</actions>

=== RapidInfoSys/Rapid/WebContent/WEB-INF/actions/event.action.xml
<?xml version="1.0" encoding="UTF-8" ?>
<actions xmlVersion="1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schemas/action.xsd">

<!-- 

Copyright (C) 2018 - Gareth Edwards / Rapid Information Systems

gareth.edwards@rapid-is.co.uk


This file is part of the Rapid Application Platform

Rapid is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version. The terms require you to include
the original copyright, and the license notice in all redistributions.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
in a file named "COPYING".  If not, see <http://www.gnu.org/licenses/>.

 -->

    <action>
    
        <type>event</type>
        <name>Event</name>
	    <class>com.rapid.actions.Event</class>
	    <helpHtml>This action offers a complete list of all available events on the page. Selecting any event from this action will trigger all of the associated actions on that particular event.</helpHtml>
	    
	    <addToNewApplications>false</addToNewApplications>
	    	    	    	    
	    <properties>
	        
	        <property>
	            <key>event</key>
	            <name>Event</name>
	            <changeValueJavaScript>select</changeValueJavaScript>
	            <getValuesFunction>
	                <![CDATA[
return "<option value=''>None</option>" + getEventOptions(this.event);
	                ]]>
	            </getValuesFunction>
	            <helpHtml>Selects a set of actions to be carried out as a single event, all at once.</helpHtml>
	        </property>
	        
	    </properties>
	    	   	    	    	    	    	     	     	    
    </action>
</actions>

=== RapidInfoSys/Rapid/WebContent/WEB-INF/actions/existing.action.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<actions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schemas/action.xsd">

<!-- 

Copyright (C) 2014 - Gareth Edwards / Rapid Information Systems

gareth.edwards@rapid-is.co.uk


This file is part of the Rapid Application Platform

RapidSOA is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version. The terms require you to include
the original copyright, and the license notice in all redistributions.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
in a file named "COPYING".  If not, see <http://www.gnu.org/licenses/>.

 -->

    <action>
    
        <type>existing</type>
        <name>Existing</name>	        
	    <class>com.rapid.actions.Existing</class>
	    
	    <addToNewApplications>true</addToNewApplications>
<!-- 

This action runs actions that already exist on other controls		
		
-->	    	
		<properties>
	        <property>
	            <key>action</key>
	            <name>Action</name>
	            <changeValueJavaScript>select</changeValueJavaScript>
	            <getValuesFunction>
	                <![CDATA[
return "<option value=''>None</option>" + getExistingActionOptions(this.action, this.id);	                
	                ]]>
	            </getValuesFunction>	 
	        </property>
	    </properties>
  
    </action> 
</actions>

=== RapidInfoSys/Rapid/WebContent/WEB-INF/actions/control.action.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<actions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schemas/action.xsd">
    <action>
    
        <type>control</type>        
        <name>Control</name>	        
	    <class>com.rapid.actions.Control</class>
	     
<!-- 

This action runs JQuery functions against specific controls		
		
-->	    	
	    <properties>
		    <property>
	            <key>control</key>
	            <name>Control</name>
	            <changeValueJavaScript>select</changeValueJavaScript>	 
	            <getValuesFunction>return getControlOptions(this.control);</getValuesFunction>
	        </property>
		    <property>
	            <key>command</key>
	            <name>Command</name>
	            <setConstructValueFunction>return "// Enter JQuery command here. The event object is passed in as \"ev\"";</setConstructValueFunction>
	            <changeValueJavaScript>bigtext</changeValueJavaScript>	 
	        </property>
	    </properties>
	    <actionJavaScript>
function Action_control(actions) {
	for (var i in actions) {
		var action = actions[i];
		$("#" + action.id)[action["function"]](action.value);
	}	
}	        
	    </actionJavaScript>    
    </action> 
</actions>

=== RapidInfoSys/Rapid/WebContent/WEB-INF/actions/form.action.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<actions xmlVersion="1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schemas/action.xsd">

<!-- 

Copyright (C) 2014 - Gareth Edwards / Rapid Information Systems

gareth.edwards@rapid-is.co.uk


This file is part of the Rapid Application Platform

RapidSOA is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version. The terms require you to include
the original copyright, and the license notice in all redistributions.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
in a file named "COPYING".  If not, see <http://www.gnu.org/licenses/>.

 -->

    <action>
    
        <type>form</type>        
        <name>Form</name>	        
	    <class>com.rapid.actions.Form</class>
	    
	    <addToNewApplications>false</addToNewApplications>
	     
<!-- 

This action runs form - specifc functions
		
-->	    	
	    <properties>
	        	        
	        <property>
	            <key>actionType</key>
	            <name>Action</name>
	            <setConstructValueFunction>return ""</setConstructValueFunction>
	            <changeValueJavaScript>select</changeValueJavaScript>	 	            
	            <getValuesFunction>return [["","Please select..."],["next","next page"],["prev","previous page"],["id","copy form id"],["val","copy form value"],["err","copy form error message"],["res","copy form resume url"],["pdf","copy form pdf url"]];</getValuesFunction>	            
	            <refreshProperties>true</refreshProperties>	            
	        </property>
	        
	        <property>
	            <key>dataSource</key>
	            <name>Source</name>
	            <changeValueJavaScript>formDataSource</changeValueJavaScript> 
	            <getValuesFunction>
	                 <![CDATA[
	                // return the list of all controls on the page with the one for this action selected
	                return "<option value=''>Please select...</option>" + getFormValueOptions(this.dataSource);
	               	]]>
	            </getValuesFunction>
	        </property>
	        
	        <property>
	            <key>dataDestination</key>
	            <name>Destination</name>
	            <changeValueJavaScript>formDataDestination</changeValueJavaScript> 
	            <getValuesFunction>
	                 <![CDATA[
	                // return the list of all controls on the page with the one for this action selected
	                return "<option value=''>Please select...</option>" + getOutputOptions(this.dataDestination);
	               	]]>
	            </getValuesFunction>
	        </property>
	        
		</properties>
	
	    <resources>
	        <resource>
	            <type>css</type>
	            <contents>
	    			<![CDATA[
	    			
.formSummaryTitle {
	margin-left:20px;
}	    			
	    			
.formSummaryPage {
	margin-left:20px;
	margin-right:20px;
	margin-bottom:20px;
	padding: 10px;
	border: 3px solid black;
}

.formSummaryPage h2 {
	margin-top:0;
}

.formSummaryPage a {
	float: right;
	position:relative;
	top: -20px
}

.formSummaryControl {
	display: block;
	margin-bottom:5px;
}

.formSummarySubmit {
	margin-left:20px;
}		    			
	    			]]>        
	            </contents>
	        </resource>
	    </resources>
	        		    	        
    </action> 
</actions>

=== RapidInfoSys/Rapid/WebContent/WEB-INF/actions/logic.action.xml
<?xml version="1.0" encoding="UTF-8" ?>
<actions xmlVersion="1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schemas/action.xsd">

<!-- 

Copyright (C) 2014 - Gareth Edwards / Rapid Information Systems

gareth.edwards@rapid-is.co.uk


This file is part of the Rapid Application Platform

RapidSOA is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version. The terms require you to include
the original copyright, and the license notice in all redistributions.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
in a file named "COPYING".  If not, see <http://www.gnu.org/licenses/>.

 -->

    <action>
    
        <type>logic</type>
        <name>Logic</name>	        
	    <class>com.rapid.actions.Logic</class>	
	    
	    <addToNewApplications>true</addToNewApplications> 
	    	    	    	    
	    <properties>
	        <property>
	            <key>value1</key>
	            <name>Value 1</name>
	            <changeValueJavaScript>logicValue</changeValueJavaScript>	 
	        </property>	 
	        <property>
	            <key>operation</key>
	            <name>Operation</name>
	            <setConstructValueFunction>return "==";</setConstructValueFunction>
	            <changeValueJavaScript>select</changeValueJavaScript>	
	            <getValuesFunction>
	                <![CDATA[
return [["==","= equals"],["!=","!= doesn't equal"],[">","> greater than"],[">=",">= greater than or equal to"],["<","< less than"],["<=","<= less than or equal to"]];
					]]>
	            </getValuesFunction>	 
	        </property>	 
	        <property>
	            <key>value2</key>
	            <name>Value 2</name>
	            <changeValueJavaScript>logicValue</changeValueJavaScript>	 
	        </property>	 
	        <property>
	            <key>trueActions</key>
	            <name>Actions if true</name>
	            <changeValueJavaScript>childActions</changeValueJavaScript>	 
	        </property>
	        <property>
	            <key>falseActions</key>
	            <name>Actions if false</name>
	            <changeValueJavaScript>childActions</changeValueJavaScript>	 
	        </property>      
	    </properties>	 
	    	   	    	    	    	    	     	     	    
    </action> 
</actions>

=== RapidInfoSys/Rapid/WebContent/WEB-INF/actions/group.action.xml
<?xml version="1.0" encoding="UTF-8" ?>
<actions xmlVersion="1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schemas/action.xsd">

<!-- 

Copyright (C) 2017 - Gareth Edwards / Rapid Information Systems

gareth.edwards@rapid-is.co.uk


This file is part of the Rapid Application Platform

Rapid is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version. The terms require you to include
the original copyright, and the license notice in all redistributions.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
in a file named "COPYING".  If not, see <http://www.gnu.org/licenses/>.

 -->

    <action>
    
        <type>group</type>
        <name>Group</name>
	    <class>com.rapid.actions.Group</class>
	    <helpHtml>Enables multiple action calls in a single event. This is useful for when you want to trigger many events without taking up a lot of space. Related actions can be recalled, be formed in logical groups and can be reused in a single step. Grouped actions are also useful for page reuse events.</helpHtml>
	      
	    <properties>
	        	        
	        <property>
	            <key>actions</key>
	            <name>Actions</name>
	            <changeValueJavaScript>childActions</changeValueJavaScript>
	            <helpHtml>Add actions to this group to tidy your application, or re-use all actions in the group.</helpHtml>
	        </property>
	        	            
	    </properties>
	    	   	    	    	    	    	     	     	    
    </action>
</actions>
