=== RapidInfoSys/Rapid/WebContent/WEB-INF/schemas/action.xsd
<?xml version="1.0" encoding="ISO-8859-1" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:annotation>
		<xs:documentation>The schema for .action.xml files</xs:documentation>
	</xs:annotation>
	<xs:element name="actions">
		<xs:annotation>
			<xs:documentation>Each .action.xml file can describe several actions
			</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="action" minOccurs="1" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>The action xml is turned into json and loaded
							into the designer where it is used to create new objects
						</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="type">
								<xs:annotation>
									<xs:documentation>The action type is used to uniquely identify
										this control, it should not contain spaces or punctuation
									</xs:documentation>
								</xs:annotation>
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:pattern value="[a-zA-Z0-9_]{1,}" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="name">
								<xs:annotation>
									<xs:documentation>The action name is presented to users when
										describing, or logging something about this action
									</xs:documentation>
								</xs:annotation>
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="1" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="class">
								<xs:annotation>
									<xs:documentation>Each action must have a Java class, in the
										classpath, that extends com.rapid.desktop.Action
									</xs:documentation>
								</xs:annotation>
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="1" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="addToNewApplications" type="xs:boolean"
								minOccurs="0">
								<xs:annotation>
									<xs:documentation>If set to true the action will be added to
										new applications when they are created
									</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="resources" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="resource" minOccurs="1"
											maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="type">
														<xs:annotation>
															<xs:documentation>The javascriptFile and cssFile are
																written into the document includes, the plain javascript
																is written to the rapid.js file and the plain css is
																written to the application rapid.css file
															</xs:documentation>
														</xs:annotation>
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:enumeration value="javascriptFile" />
																<xs:enumeration value="cssFile" />
																<xs:enumeration value="javascript" />
																<xs:enumeration value="css" />
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="contents">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:minLength value="1" />
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="properties" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="property" minOccurs="1"
											maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="key">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:minLength value="1" />
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="name">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:minLength value="1" />
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="setConstructValueFunction"
														minOccurs="0">
														<xs:annotation>
															<xs:documentation>Leave this out to not set a property
																value when the control is constructed
															</xs:documentation>
														</xs:annotation>
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:minLength value="1" />
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="changeValueJavaScript">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:minLength value="1" />
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="getValuesFunction" minOccurs="0">
														<xs:annotation>
															<xs:documentation>Possible values that can be used to
																create selects, radio groups, etc
															</xs:documentation>
														</xs:annotation>
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:minLength value="1" />
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="actionJavaScript" minOccurs="0">
								<xs:annotation>
									<xs:documentation>This is the client-side JavaScript that will
										be called, that actually performs the action. Typically the
										properties will be passed in
									</xs:documentation>
								</xs:annotation>
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="1" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== RapidInfoSys/Rapid/WebContent/WEB-INF/actions/mobile.action.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<actions xmlVersion="1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schemas/action.xsd">

<!-- 

Copyright (C) 2014 - Gareth Edwards / Rapid Information Systems

gareth.edwards@rapid-is.co.uk


This file is part of the Rapid Application Platform

RapidSOA is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version. The terms require you to include
the original copyright, and the license notice in all redistributions.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
in a file named "COPYING".  If not, see <http://www.gnu.org/licenses/>.

 -->

    <action>
    
        <type>mobile</type>
        <name>Mobile</name>	        
	    <class>com.rapid.actions.Mobile</class>
	    
	    <addToNewApplications>false</addToNewApplications>
<!-- 

This action runs actions that already exist on other controls		
		
-->	    	
		<properties>
		    
	        <property>
	            <key>actionType</key>
	            <name>Type</name>
	            <setConstructValueFunction>return "dial";</setConstructValueFunction>
	            <changeValueJavaScript>mobileActionType</changeValueJavaScript>	 
	            <refreshProperties>true</refreshProperties>
	        </property>
	        
	        <property>
	            <key>numberControlId</key>
	            <name>Phone number source</name>
	             <visible>false</visible>
	            <changeValueJavaScript>select</changeValueJavaScript>	 
	             <getValuesFunction>
	                <![CDATA[
return "<option value=''>Please select...</option>" + getInputOptions(this.numberControlId);	                
	                ]]>
	            </getValuesFunction>
	        </property>
	        
	        <property>
	            <key>numberField</key>
	            <name>Phone number source field</name>
	             <visible>false</visible>
	            <changeValueJavaScript>text</changeValueJavaScript>	 
	        </property>
	        
	        <property>
	            <key>messageControlId</key>
	            <name>Message source</name>
	             <visible>false</visible>
	            <changeValueJavaScript>select</changeValueJavaScript>	
	             <getValuesFunction>
	                <![CDATA[
return "<option value=''>Please select...</option>" + getInputOptions(this.messageControlId);	                
	                ]]>
	            </getValuesFunction> 	           
	        </property>
	        
	        <property>
	            <key>messageField</key>
	            <name>Message source field</name>
	             <visible>false</visible>
	            <changeValueJavaScript>text</changeValueJavaScript>	 	            
	        </property>
	        
	        <property>
	            <key>galleryControlId</key>
	            <name>Gallery control</name>
	            <visible>false</visible>
	            <changeValueJavaScript>select</changeValueJavaScript>
	            <getValuesFunction>
	                <![CDATA[
return "<option value=''>Please select...</option>" + getControlOptions(this.galleryControlId, null, "gallery");	                
	                ]]>
	            </getValuesFunction>	 	            
	        </property>
	        
	        <property>
	            <key>imageMaxSize</key>
	            <name>Max width/height (px)</name>
	            <visible>false</visible>
	            <setConstructValueFunction>return "500";</setConstructValueFunction>
	            <changeValueJavaScript>integer</changeValueJavaScript>	 
	        </property>
	        
	        <property>
	            <key>imageQuality</key>
	            <name>Quality (%)</name>
	            <visible>false</visible>
	            <setConstructValueFunction>return "50";</setConstructValueFunction>
	            <changeValueJavaScript>integer</changeValueJavaScript>	 
	        </property>
	        
	         <property>
	            <key>galleryControlIds</key>
	            <name>Controls</name>
	            <visible>false</visible>
	            <changeValueJavaScript>galleryControls</changeValueJavaScript>	            
	            <refreshProperties>true</refreshProperties>
	        </property>
	        
	         <property>
	            <key>barcodeDestinations</key>
	            <name>Destinations</name>
	            <visible>false</visible>
	            <changeValueJavaScript>datacopyDestinations</changeValueJavaScript>	 
	        </property> 
	        
	        <property>
	            <key>successActions</key>
	            <name>Success actions</name>
	            <visible>false</visible>
	            <changeValueJavaScript>childActions</changeValueJavaScript>	 
	        </property>
	        
	        <property>
	            <key>errorActions</key>
	            <name>Error actions</name>
	            <visible>false</visible>
	            <changeValueJavaScript>childActions</changeValueJavaScript>	 
	        </property> 
	        	        
	        <property>
	            <key>navigateControlId</key>
	            <name>Navigate to source</name>
	             <visible>false</visible>
	            <changeValueJavaScript>select</changeValueJavaScript>	 
	             <getValuesFunction>
	                <![CDATA[
return "<option value=''>Please select...</option>" + getInputOptions(this.navigateControlId);	                
	                ]]>
	            </getValuesFunction>
	        </property>
	        
	        <property>
	            <key>navigateField</key>
	            <name>Navigate to source field</name>
	             <visible>false</visible>
	            <changeValueJavaScript>text</changeValueJavaScript>	 
	        </property>
	        
	         <property>
	            <key>navigateMode</key>
	            <name>Navigation mode</name>
	            <visible>false</visible>	            
	            <setConstructValueFunction>
	                <![CDATA[
return "d";	                
	                ]]>
	            </setConstructValueFunction>
	            <changeValueJavaScript>select</changeValueJavaScript>
	            <getValuesFunction>
	                <![CDATA[
return [["d","driving"],["w","walking"],["b","cycling"],["transit","public transport"]];	                
	                ]]>
	            </getValuesFunction>	 	            
	        </property>
	        
	        <property>
	            <key>message</key>
	            <name>Message</name>
	            <visible>false</visible>
	            <changeValueJavaScript>bigtext</changeValueJavaScript>	 
	        </property>
	        	        	        
	        <property>
	            <key>gpsDestinations</key>
	            <name>Destinations</name>
	            <visible>false</visible>
	            <changeValueJavaScript>datacopyDestinations</changeValueJavaScript>	 
	        </property> 
         	        
	        <property>
	            <key>gpsFrequency</key>
	            <name>Update frequency (seconds)</name>
	            <visible>false</visible>
	            <setConstructValueFunction>return 0;</setConstructValueFunction>
	            <changeValueJavaScript>integer</changeValueJavaScript>	 
	        </property>
	        
	        <property>
	            <key>gpsCheck</key>
	            <name>Check GPS enabled</name>
	            <visible>false</visible>
	            <changeValueJavaScript>checkbox</changeValueJavaScript>	 
	        </property>
	        
	        <property>
	            <key>onlineActions</key>
	            <name>Actions</name>
	            <visible>false</visible>
	            <changeValueJavaScript>childActions</changeValueJavaScript>	 
	        </property>
	        
	        <property>
	            <key>onlineWorking</key>
	            <name>Working dialogue</name>
	            <visible>false</visible>
	            <changeValueJavaScript>navigationPage</changeValueJavaScript>	 
	        </property>
	        
	        <property>
	            <key>onlineFail</key>
	            <name>Offline dialogue</name>
	            <visible>false</visible>
	            <changeValueJavaScript>navigationPage</changeValueJavaScript>	 
	        </property>
	        
	    </properties>
	    
		<resources>
		    
	        <resource>
	            <type>javascriptFile</type>
	            <contents>
	               scripts/controls/map.js
	            </contents>
            </resource>
            
		</resources>
	    
		<actionJavaScript>
	        <![CDATA[ 
	          
function Action_mobile(actionId, type) {
	// action callback
	alert("Callback for " + actionId + "." + type);
}	        

			]]>
	    </actionJavaScript>
	    
    </action> 
</actions>

=== RapidInfoSys/Rapid/WebContent/WEB-INF/actions/listfolder.action.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<actions xmlVersion="1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schemas/action.xsd">

<!-- 

Copyright (C) 2016 - Gareth Edwards / Rapid Information Systems

gareth.edwards@rapid-is.co.uk

This file is part of the Rapid Application Platform

Rapid is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version. The terms require you to include
the original copyright, and the license notice in all redistributions.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
in a file named "COPYING".  If not, see <http://www.gnu.org/licenses/>.

 -->

    <action>
    
        <type>listfolder</type>
        <name>List folder</name>
	    <class>com.rapid.actions.ListFolder</class>
	    
	    <properties>
	        <property>
	            <key>rootFolder</key>
	            <name>Root folder</name>
	            <changeValueJavaScript>text</changeValueJavaScript>
	            <helpHtml>Sets the folder to read the file properties from..</helpHtml>
	        </property>
	        
	        <property>
	            <key>dataDestination</key>
	            <name>Destination</name>
	            <changeValueJavaScript>select</changeValueJavaScript>
	            <getValuesFunction>
	                 <![CDATA[
	                // return the list of all controls on the page with the one for this action selected
	                return "<option value=''>Please select...</option>" + getOutputOptions(this.dataDestination);
	               	]]>
	            </getValuesFunction>
	            <helpHtml>Sets the destination for where the folder listing is being copied to.</helpHtml>
	        </property>
	        
	        <property>
	            <key>showHidden</key>
	            <name>Show hidden files</name>
	            <changeValueJavaScript>checkbox</changeValueJavaScript>
	            <getValuesFunction>return false;</getValuesFunction>
	            <helpHtml>Sets whether to show the hidden files in the current root or not.</helpHtml>
	        </property>
	    </properties>
	    		    	        
    </action> 
</actions>
