=== RapidInfoSys/Rapid/WebContent/WEB-INF/schemas/theme.xsd
<?xml version="1.0" encoding="ISO-8859-1" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<!-- 

Copyright (C) 2016 - Gareth Edwards / Rapid Information Systems

gareth.edwards@rapid-is.co.uk


This file is part of the Rapid Application Platform

Rapid is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version. The terms require you to include
the original copyright, and the license notice in all redistributions.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
in a file named "COPYING".  If not, see <http://www.gnu.org/licenses/>.

 -->

	<xs:annotation>
		<xs:documentation>The schema for .template.xml files</xs:documentation>
	</xs:annotation>
	<xs:element name="template">
		<xs:annotation>
			<xs:documentation>Each .template.xml file describes a single template
			</xs:documentation>
		</xs:annotation>
		
		<xs:complexType>
			<xs:sequence>
			
				<xs:element name="type">
					<xs:annotation>
						<xs:documentation>The template type is used to uniquely identify
							this control, it should not contain spaces or punctuation
						</xs:documentation>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:pattern value="[a-zA-Z0-9_]{1,}" />
						</xs:restriction>
					</xs:simpleType>
				</xs:element>		
									
				<xs:element name="name">
					<xs:annotation>
						<xs:documentation>The template name is used presented to users
							when describing, or logging something about this control
						</xs:documentation>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="1" />
						</xs:restriction>
					</xs:simpleType>
				</xs:element>				
				
				<xs:element name="resources" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="resource" minOccurs="1"
								maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="type">
											<xs:annotation>
												<xs:documentation>
													The contents of the plain javascript is written to the rapid.js file and the plain css is written to the application rapid.css file. 
													The javascriptFile and cssFile are written into the html head section includes as links, these are replaced with minified versions for live applications.
													The javascriptLink and cssLink are written into the html head section includes as links, but no minified version are made. 
													The file type resources	are included in the off-line download
												</xs:documentation>
											</xs:annotation>
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:enumeration value="javascript" />
													<xs:enumeration value="css" />																
													<xs:enumeration value="javascriptFile" />
													<xs:enumeration value="cssFile" />																
													<xs:enumeration value="javascriptLink" />
													<xs:enumeration value="cssLink" />
													<xs:enumeration value="file" />
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="contents">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:minLength value="1" />
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				
				<xs:element name="css">
					<xs:annotation>
						<xs:documentation>The template name is used presented to users
							when describing, or logging something about this control
						</xs:documentation>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="1" />
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				
			<xs:element name="headerHtml" minOccurs="0">
				<xs:annotation>
					<xs:documentation>HTML that will be included immediately after the body element in all pages, including form summary.
					</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="1" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
	
			<xs:element name="footerHtml" minOccurs="0">
				<xs:annotation>
					<xs:documentation>HTML that will be included immediately before the closing body element in all pages, including form summary.
					</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="1" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
				
			</xs:sequence>
			<xs:attribute name="xmlVersion" type="xs:integer" use="required">
				<xs:annotation>
					<xs:documentation>This attribute defines the version of the xml file</xs:documentation>
				</xs:annotation>
			</xs:attribute>
	
		</xs:complexType>
				
	</xs:element>
</xs:schema>

=== RapidInfoSys/Rapid/WebContent/WEB-INF/themes/bootstrap.theme.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<template xmlVersion="1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schemas/theme.xsd">

<!-- 

Copyright (C) 2016 - Gareth Edwards / Rapid Information Systems

gareth.edwards@rapid-is.co.uk


This file is part of the Rapid Application Platform

Rapid is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version. The terms require you to include
the original copyright, and the license notice in all redistributions.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
in a file named "COPYING".  If not, see <http://www.gnu.org/licenses/>.

 -->



<type>bootstrap</type>
<name>Bootstrap</name>

<resources>
	
	<resource>
		<type>cssLink</type>
		<contents>styles/bootstrap.css</contents>
	</resource>

	<resource>
		<type>cssLink</type>
		<contents>styles/override.css</contents>
	</resource>

	<resource>
		<type>javascriptLink</type>
		<contents>scripts/bootstrap.min.js</contents>
	</resource>

	<resource>
		<type>javascriptLink</type>
		<contents>scripts/modernizr.js</contents>
	</resource>

	<resource>
		<type>javascriptLink</type>
		<contents>scripts/jquery.tablesorter.js</contents>
	</resource>

	<resource>
		<type>javascriptLink</type>
		<contents>scripts/tablesorter.scroller.js</contents>
	</resource>

	<resource>
		<type>javascriptLink</type>
		<contents>scripts/scripts.js</contents>
	</resource>
	
</resources>

<css>
	<![CDATA[

.spacer {
  margin-bottom: 20px;
}

/* 
  Bootstrap classes - thanks to https://gist.github.com/geksilla/6543145
  Jst listed here so they come through in the designer

.active {}
.affix {}
.alert {}
.alert-danger {}
.alert-dismissable {}
.alert-info {}
.alert-link {}
.alert-success {}
.alert-warning {}
.arrow {}
.badge {}
.bottom {}
.breadcrumb {}
.btn {}
.btn-block {}
.btn-danger {}
.btn-default {}
.btn-group {}
.btn-group-justified {}
.btn-group-vertical {}
.btn-info {}
.btn-lg {}
.btn-link {}
.btn-primary {}
.btn-success {}
.btn-warning {}
.btn-xs {}
.caption {}
.caret {}
.carousel {}
.carousel-caption {}
.carousel-control {}
.carousel-indicators {}
.carousel-inner {}
.checkbox {}
.checkbox-inline {}
.check-input {}
.check-radio {}
.close {}
.col {}
.col-lg-1 {}
.col-lg-10 {}
.col-lg-11 {}
.col-lg-12 {}
.col-lg-2 {}
.col-lg-3 {}
.col-lg-4 {}
.col-lg-5 {}
.col-lg-6 {}
.col-lg-7 {}
.col-lg-8 {}
.col-lg-9 {}
.col-lg-offset-0 {}
.col-lg-offset-1 {}
.col-lg-offset-10 {}
.col-lg-offset-11 {}
.col-lg-offset-2 {}
.col-lg-offset-3 {}
.col-lg-offset-4 {}
.col-lg-offset-5 {}
.col-lg-offset-6 {}
.col-lg-offset-7 {}
.col-lg-offset-8 {}
.col-lg-offset-9 {}
.col-lg-pull-0 {}
.col-lg-pull-1 {}
.col-lg-pull-10 {}
.col-lg-pull-11 {}
.col-lg-pull-2 {}
.col-lg-pull-3 {}
.col-lg-pull-4 {}
.col-lg-pull-5 {}
.col-lg-pull-6 {}
.col-lg-pull-7 {}
.col-lg-pull-8 {}
.col-lg-pull-9 {}
.col-lg-push-0 {}
.col-lg-push-1 {}
.col-lg-push-10 {}
.col-lg-push-11 {}
.col-lg-push-2 {}
.col-lg-push-3 {}
.col-lg-push-4 {}
.col-lg-push-5 {}
.col-lg-push-6 {}
.col-lg-push-7 {}
.col-lg-push-8 {}
.col-lg-push-9 {}
.col-md-1 {}
.col-md-10 {}
.col-md-11 {}
.col-md-12 {}
.col-md-2 {}
.col-md-3 {}
.col-md-4 {}
.col-md-5 {}
.col-md-6 {}
.col-md-7 {}
.col-md-8 {}
.col-md-9 {}
.col-md-offset-0 {}
.col-md-offset-1 {}
.col-md-offset-10 {}
.col-md-offset-11 {}
.col-md-offset-2 {}
.col-md-offset-3 {}
.col-md-offset-4 {}
.col-md-offset-5 {}
.col-md-offset-6 {}
.col-md-offset-7 {}
.col-md-offset-8 {}
.col-md-offset-9 {}
.col-md-pull-0 {}
.col-md-pull-1 {}
.col-md-pull-10 {}
.col-md-pull-11 {}
.col-md-pull-2 {}
.col-md-pull-3 {}
.col-md-pull-4 {}
.col-md-pull-5 {}
.col-md-pull-6 {}
.col-md-pull-7 {}
.col-md-pull-8 {}
.col-md-pull-9 {}
.col-md-push-0 {}
.col-md-push-1 {}
.col-md-push-10 {}
.col-md-push-11 {}
.col-md-push-2 {}
.col-md-push-3 {}
.col-md-push-4 {}
.col-md-push-5 {}
.col-md-push-6 {}
.col-md-push-7 {}
.col-md-push-8 {}
.col-md-push-9 {}
.col-sm-1 {}
.col-sm-10 {}
.col-sm-11 {}
.col-sm-12 {}
.col-sm-2 {}
.col-sm-3 {}
.col-sm-4 {}
.col-sm-5 {}
.col-sm-6 {}
.col-sm-7 {}
.col-sm-8 {}
.col-sm-9 {}
.col-sm-offset-1 {}
.col-sm-offset-10 {}
.col-sm-offset-11 {}
.col-sm-offset-2 {}
.col-sm-offset-3 {}
.col-sm-offset-4 {}
.col-sm-offset-5 {}
.col-sm-offset-6 {}
.col-sm-offset-7 {}
.col-sm-offset-8 {}
.col-sm-offset-9 {}
.col-sm-pull-1 {}
.col-sm-pull-10 {}
.col-sm-pull-11 {}
.col-sm-pull-2 {}
.col-sm-pull-3 {}
.col-sm-pull-4 {}
.col-sm-pull-5 {}
.col-sm-pull-6 {}
.col-sm-pull-7 {}
.col-sm-pull-8 {}
.col-sm-pull-9 {}
.col-sm-push-1 {}
.col-sm-push-10 {}
.col-sm-push-11 {}
.col-sm-push-2 {}
.col-sm-push-3 {}
.col-sm-push-4 {}
.col-sm-push-5 {}
.col-sm-push-6 {}
.col-sm-push-7 {}
.col-sm-push-8 {}
.col-sm-push-9 {}
.col-xs-1 {}
.col-xs-10 {}
.col-xs-11 {}
.col-xs-12 {}
.col-xs-2 {}
.col-xs-3 {}
.col-xs-4 {}
.col-xs-5 {}
.col-xs-6 {}
.col-xs-7 {}
.col-xs-8 {}
.col-xs-9 {}
.collapse {}
.collapsing {}
.container {}
.control-label {}
.divider {}
.dropdown {}
.dropdown-backdrop {}
.dropdown-header {}
.dropdown-menu {}
.dropdown-toggle {}
.fade {}
.focusBorder {}
.form-control {}
.form-control-static {}
.form-group {}
.glyphicon {}
.glyphicon-chevron-right {}
.h1 {}
.h2 {}
.h3 {}
.h4 {}
.h5 {}
.h6 {}
.has-warning {}
.has-error {}
.has-success {}
.help-block {}
.hidden {}
.hidden-lg {}
.hidden-md {}
.hidden-print {}
.hidden-sm {}
.hidden-xs {}
.hide {}
.icon-bar {}
.icon-next {}
.img-circle {}
.img-responsive {}
.img-rounded {}
.img-thumbnail {}
.in {}
.initialism {}
.input-group {}
.input-group-addon {}
.input-group-btn {}
.input-lg {}
.input-sm {}
.invisible {}
.item {}
.jumbotron {}
.label {}
.label-danger {}
.label-default {}
.label-info {}
.label-primary {}
.label-success {}
.label-warning {}
.lead {}
.left {}
.list-group {}
.list-group-item {}
.list-group-item-heading {}
.list-group-item-text {}
.list-inline {}
.list-unstyled {}
.media {}
.media-body {}
.media-heading {}
.media-list {}
.media-object {}
.modal {}
.modal-backdrop {}
.modal-body {}
.modal-content {}
.modal-dialog {}
.modal-footer {}
.modal-header {}
.modal-open {}
.modal-title {}
.nav {}
.nav-divider {}
.nav-justified {}
.nav-tabs {}
.nav-tabs-justified {}
.navbar {}
.navbar-brand {}
.navbar-btn {}
.navbar-collapse {}
.navbar-default {}
.navbar-fixed-bottom {}
.navbar-fixed-top {}
.navbar-form {}
.navbar-header {}
.navbar-inverse {}
.navbar-left {}
.navbar-link {}
.navbar-nav {}
.navbar-right {}
.navbar-static-top {}
.navbar-text {}
.navbar-toggle {}
.next {}
.page-header {}
.pager {}
.pagination {}
.panel {}
.panel-body {}
.panel-danger {}
.panel-default {}
.panel-footer {}
.panel-heading {}
.panel-info {}
.panel-primary {}
.panel-success {}
.panel-title {}
.panel-warning {}
.pill-pane {}
.popover {}
.popover-content {}
.popover-title {}
.pre-scrollable {}
.prettyprint {}
.prev {}
.progress {}
.progress-bar {}
.progress-bar-danger {}
.progress-bar-info {}
.progress-bar-success {}
.progress-bar-warning {}
.pull-left {}
.pull-right {}
.right {}
.row {}
.show {}
.sr-only {}
.table {}
.table-bordered {}
.table-responsive {}
.text-center {}
.text-danger {}
.text-hide {}
.text-info {}
.text-left {}
.text-muted {}
.text-primary {}
.text-right {}
.text-success {}
.text-warning {}
.thumbnail {}
.tooltip {}
.tooltip-arrow {}
.tooltip-inner {}
.top {}
.visible-lg {}
.visible-md {}
.visible-print {}
.visible-sm {}
.visible-xs {}
.well {}
.well-lg {}
.well-sm {}
.wrapper {}
*/

]]>
</css>

</template>
